### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, open 'C:\LLTG.local\TESTDEV-27-05-16\UAA\ts_uaaCl...

### ISSUE THREAD

**Issue by fastboyz** [pvorona/atom-idle-autosave#1]
[Enter steps to reproduce below:]
1. have a document open
2. make another  program modify it in the back ground

**Atom Version**: 1.7.4
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-idle-autosave](https://github.com/pvorona/atom-idle-autosave) package, v0.3.0
### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open '%filePath%'

```
At C:\Users\userName\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1108

Error: EBUSY: resource busy or locked, open %filePath%t'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (C:\Users\UserName\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (C:\Users\smmiengue\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\UserName\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:420:21)
    at File.module.exports.File.writeSync (C:\Users\UserName\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:377:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\UserName\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\UserName\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\UserName\AppData\Local\atom\app-1.7.4\resources\app.asar\src\text-editor.js:660:26)
    at Object.save (file:///C:/Users/UserName/.atom/packages/atom-idle-autosave/lib/atom-idle-autosave.coffee:8:10)
    at invokeFunc (C:\Users\UserName\.atom\packages\atom-idle-autosave\node_modules\lodash\lodash.js:9657:23)
    at trailingEdge (C:\Users\UserName\.atom\packages\atom-idle-autosave\node_modules\lodash\lodash.js:9704:18)
    at timerExpired (C:\Users\UserName\.atom\packages\atom-idle-autosave\node_modules\lodash\lodash.js:9692:18)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
atom-idle-autosave, v0.3.0
atom-save-all, v0.4.1
atomic-chrome, v0.3.0
minimap, v4.24.2

# Dev
No dev packages
```

**Comment by pvorona** [comment]
@fastboyz , how do you think what should be done in this case?

**Comment by fastboyz** [comment]
@pvorona  I would probably look if the file has a lock on another program and not try to save it
