### ISSUE TITLE
Uncaught Error: Can't save destroyed buffer

### ISSUE THREAD

**Issue by giulianolatini** [pvorona/atom-idle-autosave#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-idle-autosave](https://github.com/pvorona/atom-idle-autosave) package 0.3.0

### Stack Trace

Uncaught Error: Can't save destroyed buffer

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1055

Error: Can't save destroyed buffer
  at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1055:15)
  at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
  at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:890:26)
  at Object.save (/packages/atom-idle-autosave/lib/atom-idle-autosave.coffee:8:10)
  at invokeFunc (/packages/atom-idle-autosave/node_modules/lodash/lodash.js:10350:23)
  at trailingEdge (/packages/atom-idle-autosave/node_modules/lodash/lodash.js:10397:18)
  at timerExpired (/packages/atom-idle-autosave/node_modules/lodash/lodash.js:10385:18)

```

### Commands

```
     -1:30.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
.bin undefined 
academic 0.34.1 
atom-beautify 0.29.17 
atom-idle-autosave 0.3.0 
atom-javascript-console-snippets 0.10.0 
atom-material-numix-syntax 0.2.1 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-memolist-grep 0.4.0 
atom-memolist-new 0.4.0 
atom-polymer 0.13.0 
atom-sync 0.7.3 
atom-terminal 0.8.0 
atom-ternjs 0.17.1 
auto-detect-indentation 1.3.0 
auto-update-packages 1.0.1 
autocomplete 0.47.0 
autocomplete-html-entities 0.1.0 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-polymer-project 0.2.1 
colorful-json 1.1.0 
creative-dark-syntax 1.1.0 
dash 1.7.0 
docblockr 0.9.1 
docker 0.7.0 
dockerletion 0.2.0 
editorconfig 2.2.0 
ember-snippets 1.4.0 
emmet 2.4.3 
environment 1.3.1 
es6-javascript 1.0.0 
file-icons 2.0.15 
flatten-json 0.1.5 
git-control 0.8.2 
git-go undefined 
git-history 3.2.0 
git-log 0.4.1 
git-projects 1.17.0 
git-tab-status 1.7.0 
gitignore-snippets 0.2.5 
go-debug 1.0.4 
go-find-references 1.2.3 
go-imports 0.1.1 
go-plus 5.1.1 
go-rename 0.3.0 
go-signature-statusbar 1.2.0 
gulp-snippets 0.6.2 
highlight-line 0.12.0 
hyperclick 0.0.40 
javascript-snippets 1.2.1 
js-patterns-atom-snippets 0.2.1 
jshint 1.8.6 
json-colorer 1.0.0 
json-converter 0.2.4 
language-autotools 2.0.1 
language-babel 2.54.1 
language-docker 1.1.7 
language-dots 0.0.4 
language-javascript-better 1.7.1 
language-javascript-jsx 0.3.7 
language-javascript-semantic 0.2.1 
language-json-comments 0.16.3 
language-jsx 0.1.1 
language-protobuf 0.7.1 
language-viml 1.1.3 
less-than-slash 0.16.0 
linter 1.11.22 
linter-docker 0.1.4 
linter-eslint 8.1.1 
linter-flow 5.5.0 
linter-golint 0.3.0 
linter-golinter 1.2.1 
linter-gotype 0.1.0 
linter-htmlhint undefined 
linter-jscs 4.1.1 
linter-jsl 0.0.1 
linter-jsxhint 0.1.2 
linter-metascript 0.0.5 
linter-tslint 0.13.1 
linter-write-good 0.8.0 
markdown-assistant 0.2.0 
markdown-deluxe 1.0.0 
markdown-format 2.5.1 
markdown-helpers 0.3.0 
material 2.2.0 
material-syntax 0.6.1 
minimap 4.26.8 
modular-snippets 0.2.1 
nuclide-flow 0.0.35 
open-recent 5.0.0 
open-terminal-here 2.2.0 
pigments 0.39.0 
pinegrow-atom 0.3.1 
polymer-snippets 3.2.1 
polymerjs-snippets 2.1.0 
pretty-json 1.6.1 
react-snippets 0.6.3 
remote-sync 4.1.5 
semantic-ui 1.0.9 
standard-formatter 2.8.0 
symbols-tree-view 0.13.2 
sync-settings 0.8.1 
tabularize 0.2.5 
term3 0.22.1 
Termrk 0.3.1 
todo-show 1.10.0 
toggle-markdown-task 0.6.0 
tool-bar 1.0.1 
tree-view-git-projects 0.5.0 
tree-view-git-status 1.3.0 
turbo-javascript 1.4.0 
unity-ui 2.1.8 
vagrant 0.1.0 
xeta-syntax 0.5.0 
```

**Comment by mmtftr** [comment]
Hello, I've just sent a pull request to fix this issue, i believe using  isEmpty() and catch will fix this issue. You can check out my pull request

**Comment by netsurferhi** [comment]
Still happening

**Comment by Idariel** [comment]
Having the same problem. Got fed up and unstalled it. Sorry, loved that package.

**Comment by mooona** [comment]
I'm having the same issue :(
